server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/Desktop/inflearn/native-file-repo
        git:
          uri: https://github.com/men16922/spring-cloud-config.git
#          uri: file:///Users/82104/Desktop/inflearn/git-local-repo

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh